base: base_link
left_front:
  - frontLeftHipRotateX
  - frontLeftHipRotateY
  - frontLeftKnee
  - frontLeftFoot

right_front:
  - frontRightHipRotateX
  - frontRightHipRotateY
  - frontRightKnee
  - frontRightFoot

left_hind:
  - backLeftHipRotateX
  - backLeftHipRotateY
  - backLeftKnee
  - backLeftFoot

right_hind:
  - backRightHipRotateX
  - backRightHipRotateY
  - backRightKnee
  - backRightFoot